version: 2
jobs:
  build:
    working_directory: ~/franz
    docker:
      - image: gradle:3.5-jdk8
    steps:
      - checkout
      - restore_cache:
          key: circleci-franz-{{ checksum "build.gradle" }}
      - run: gradle dependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: circleci-franz-{{ checksum "build.gradle" }}
      - run: gradle build
      - run: gradle test
      - store_test_results:
          path: ~/franz/build/test-results
